# Generated by Django 5.2.7 on 2025-10-26 09:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_transaction_upiconfig'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='upiconfig',
            options={},
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_id',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='upi_used',
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(choices=[('phonepe', 'PhonePe'), ('paytm', 'Paytm')], max_length=50),
        ),
        migrations.AlterField(
            model_name='upiconfig',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
