# Generated by Django 5.2.7 on 2025-10-26 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_upiconfig_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-transaction_time']},
        ),
        migrations.AlterModelOptions(
            name='upiconfig',
            options={'verbose_name': 'UPI Configuration', 'verbose_name_plural': 'UPI Configurations'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AddField(
            model_name='product',
            name='country_of_origin',
            field=models.CharField(default='India', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='details',
            field=models.JSONField(blank=True, default=list, help_text="Example: [{'label': 'Fabric', 'value': 'Cotton'}, {'label': 'Sleeve', 'value': 'Full'}]"),
        ),
        migrations.AddField(
            model_name='product',
            name='highlights',
            field=models.JSONField(blank=True, default=list, help_text="Example: [{'label': 'Color', 'value': 'Red'}, {'label': 'Pattern', 'value': 'Printed'}]"),
        ),
        migrations.AddField(
            model_name='product',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sizes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='product',
            name='sold_by',
            field=models.CharField(default='Unknown Seller', max_length=255),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='upiconfig',
            name='upi_id',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_name', models.CharField(max_length=255)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('comment', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='reviews/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='shop.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
