# Generated by Django 5.2.7 on 2025-10-26 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_remove_order_address_alter_transaction_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-id'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='productreview',
            options={'ordering': ['-created_at'], 'verbose_name': 'Product Review', 'verbose_name_plural': 'Product Reviews'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-transaction_time'], 'verbose_name': 'Transaction', 'verbose_name_plural': 'Transactions'},
        ),
        migrations.AlterModelOptions(
            name='upiconfig',
            options={'ordering': ['-created_at'], 'verbose_name': 'UPI Configuration', 'verbose_name_plural': 'UPI Configurations'},
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.PositiveIntegerField(default=0, help_text='Percentage discount'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_file',
            field=models.ImageField(blank=True, help_text='Upload product image', null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, help_text='External image link (optional)', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='sizes',
            field=models.JSONField(blank=True, default=list, help_text="Example: ['S','M','L','XL']"),
        ),
        migrations.AlterField(
            model_name='product',
            name='sold_by',
            field=models.CharField(default='Unknown Seller', help_text='Store or seller name', max_length=255),
        ),
    ]
