# Generated by Django 5.2.7 on 2025-10-26 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_order_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
        migrations.AlterModelOptions(
            name='productreview',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-transaction_time']},
        ),
        migrations.AlterModelOptions(
            name='upiconfig',
            options={'verbose_name': 'UPI Configuration', 'verbose_name_plural': 'UPI Configurations'},
        ),
        migrations.AlterField(
            model_name='product',
            name='details',
            field=models.JSONField(blank=True, default=list, help_text="List of details like [{'label': 'Fabric', 'value': 'Cotton'}]"),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='highlights',
            field=models.JSONField(blank=True, default=list, help_text="List of highlights like [{'label': 'Occasion', 'value': 'Casual'}]"),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='sold_by',
            field=models.CharField(default='Unknown Seller', max_length=255),
        ),
    ]
