# Generated by Django 5.2.7 on 2025-10-26 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_order_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-id'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='productreview',
            options={'ordering': ['-created_at'], 'verbose_name': 'Product Review', 'verbose_name_plural': 'Product Reviews'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-transaction_time'], 'verbose_name': 'Transaction', 'verbose_name_plural': 'Transactions'},
        ),
        migrations.AlterModelOptions(
            name='upiconfig',
            options={'ordering': ['-created_at'], 'verbose_name': 'UPI Configuration', 'verbose_name_plural': 'UPI Configurations'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='details',
        ),
        migrations.RemoveField(
            model_name='product',
            name='highlights',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sizes',
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, help_text='Example: Red / Random', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='fabric',
            field=models.CharField(blank=True, help_text='Example: Cotton Blend', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='fit_shape',
            field=models.CharField(blank=True, help_text='Example: Regular', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='occasion',
            field=models.CharField(blank=True, help_text='Example: Casual', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='pattern',
            field=models.CharField(blank=True, help_text='Example: Printed', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='size_3xl',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='size_4xl',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='size_5xl',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='size_6xl',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='size_7xl',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='size_8xl',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='size_l',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='size_m',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='size_s',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='size_xl',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='size_xxl',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='sleeve_length',
            field=models.CharField(blank=True, help_text='Example: Long Sleeves', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.PositiveIntegerField(default=0, help_text='Percentage discount'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_file',
            field=models.ImageField(blank=True, help_text='Upload product image', null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, help_text='External image link (optional)', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='sold_by',
            field=models.CharField(default='Unknown Seller', help_text='Store or seller name', max_length=255),
        ),
    ]
